# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/flavors
Accept: application/json

###

GET http://127.0.0.1:8000/flavors/2
Accept: application/json

###

POST http://127.0.0.1:8000/flavors
Accept: application/json
Content-Type: application/json
#Authorization: Bearer TOKEN

{
  "name": "Chocolate",
  "type": "traditional",
  "description": "Rich and creamy chocolate flavour.",
  "price": 1.35,
  "available": true
}

###
POST http://127.0.0.1:8000/users
Accept: application/json
Content-Type: application/json

{
  "email": "charlie@mail.com",
  "password": "charlie"
}

###
POST http://127.0.0.1:8000/users/token
Accept: application/json
Content-Type: application/json

{
  "email": "alice@mail.com",
  "password": "alice"
}